apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: stickyapp-rust
spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: stickyapp-rust
        image: paarijaat-debian-vm:5000/paarijaat/stickyapp_rust:v0.1.3
        resources:
          requests:
            memory: "100Mi"
            cpu: "50m"
          limits:
            memory: "200Mi"
            cpu: "400m"
        imagePullPolicy: IfNotPresent #Always
        env:
          - name: RUST_LOG
            value: "info"
        ports:
        - containerPort: 8080
